#!/usr/bin/env bash
#Displays list of currently running processes
#+ Show all processes, for all users, including those which might not have a TTY
#+ Display in a user-oriented format
#+ Shows process hierarchy

ps -a -u -x -f