#!/usr/bin/env bash
# Change localhost to 127.0.0.2
# Change facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.new
sudo sh -c "echo '127.0.0.2 localhost' >> /etc/hosts"
sudo sh -c "echo '8.8.8.8 facebook.com' >> /etc/hosts"
cp -f ~/hosts.new /etc/hosts
